package java.THIN_UEBUNG_6;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import main.java.THIN_UEBUNG_6.App;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
