package THIN_UEBUNG_6;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        Cellar cellar = new Cellar();
        System.out.println("Enter:");
        cellar.start();
    }
}
